version: "3.5"

services: 
    #  Application
    symfony:
        build:
            context: .
            dockerfile: symfony.Dockerfile
        volumes:
            - appdir:/usr/src/app
        
    # Web Server
    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        volumes: 
            - appdir:/usr/src/app
        ports:
            - 80:80
            - 443:443

volumes:
    appdir:
